import { AlertTriangle, Info, ShieldAlert, Sparkles, X } from "lucide-react";
import Modal from "../Modal";


const extractLocation = (label) => {
    if (!label) return null;   // 🔥 safety fix
    const match = label.match(/near (.+)/i);
    return match ? match[1].trim() : null;
};

// const location = extractLocation(alert.label);

export function AlertModal({ alert, onClose }) {

        const location = extractLocation(alert?.label);

    const affectedShipments = alert?.shipments?.filter(s => {
        const isActive =
            s.status === "In Transit" || s.status === "Out for Delivery";

        const sameLocation =
            location && s.dest?.toLowerCase().includes(location.toLowerCase());

        return isActive && sameLocation;
    }) || [];
    // Configuration for different alert levels
    const theme = {
        warning: {
            action: "Reroute affected shipments via NH-48. Estimated ETA impact: +35 mins.",
            color: "#D97706", // Amber-600
            bg: "#FFFBEB",
            border: "#FEF3C7",
            icon: <AlertTriangle size={20} />,
        },
        info: {
            action: "3 shipments affected. Notify clients and adjust ETAs by 2–4 hours.",
            color: "#2563EB", // Blue-600
            bg: "#EFF6FF",
            border: "#DBEAFE",
            icon: <Info size={20} />,
        },
        danger: {
            action: "Send payment reminders to BlueStar Exports, Sunrise Co., and Metro Supplies.",
            color: "#DC2626", // Red-600
            bg: "#FEF2F2",
            border: "#FEE2E2",
            icon: <ShieldAlert size={20} />,
        },
    };

    const activeTheme = theme[alert.type] || theme.info;

    return (
        <Modal onClose={onClose} width={400}>
            <div style={{ padding: "24px", position: "relative" }}>
                {/* Close Icon Button */}
                <button
                    onClick={onClose}
                    style={{
                        position: "absolute",
                        top: 16,
                        right: 16,
                        background: "none",
                        border: "none",
                        color: "#94A3B8",
                        cursor: "pointer",
                        padding: 4,
                    }}
                >
                    <X size={18} />
                </button>

                {/* Header Section */}
                <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 20 }}>
                    <div
                        style={{
                            width: 40,
                            height: 40,
                            borderRadius: 12,
                            backgroundColor: activeTheme.bg,
                            color: activeTheme.color,
                            display: "flex",
                            alignItems: "center",
                            justifyContent: "center",
                            border: `1px solid ${activeTheme.border}`,
                        }}
                    >
                        {activeTheme.icon}
                    </div>
                    <div>
                        <h3 style={{ margin: 0, fontSize: 16, fontWeight: 700, color: "#0F172A", letterSpacing: "-0.02em" }}>
                            {alert.label || "System Alert"}
                        </h3>
                        <p style={{ margin: 0, fontSize: 12, color: "#64748B" }}>Risk Analysis generated by CargoFlow AI</p>
                    </div>
                </div>

                {/* AI Action Card */}
                <div
                    style={{
                        background: "linear-gradient(135deg, #ffffff 0%, #f8fafc 100%)",
                        border: "1px solid #E2E8F0",
                        borderRadius: 16,
                        padding: "16px",
                        marginBottom: 24,
                        boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.05)",
                    }}
                >
                    <div
                        style={{
                            display: "flex",
                            alignItems: "center",
                            gap: 6,
                            fontSize: 10,
                            fontWeight: 800,
                            color: "#6366F1", // Indigo
                            textTransform: "uppercase",
                            letterSpacing: "0.1em",
                            marginBottom: 8,
                        }}
                    >
                        <Sparkles size={12} fill="#6366F1" /> AI RECOMMENDATION
                    </div>
                    <p
                        style={{
                            margin: 0,
                            fontSize: 13,
                            color: "#334155",
                            lineHeight: 1.6,
                            fontWeight: 500,
                        }}
                    >
                        {
                            affectedShipments.length > 0
                                ? `${affectedShipments.length} shipments affected. Notify clients and adjust ETAs by 2–4 hours.`
                                : "No active shipments affected."
                        }          </p>
                </div>

                {/* Action Button */}
                <button
                    onClick={onClose}
                    style={{
                        width: "100%",
                        padding: "12px 0",
                        borderRadius: 12,
                        backgroundColor: "#0F172A", // Deep Navy/Slate
                        color: "white",
                        fontSize: 14,
                        fontWeight: 600,
                        border: "none",
                        cursor: "pointer",
                        transition: "all 0.2s ease",
                        boxShadow: "0 10px 15px -3px rgba(15, 23, 42, 0.3)",
                    }}
                    onMouseEnter={(e) => (e.target.style.backgroundColor = "#1E293B")}
                    onMouseLeave={(e) => (e.target.style.backgroundColor = "#0F172A")}
                >
                    Acknowledge Risk
                </button>
            </div>
        </Modal>
    );
}