export const BASE_SHIPMENTS = [
    {
        id: "V1-20250301",
        client: "Apex Traders",
        agent: "Ravi Kumar",
        origin: "Chennai",
        dest: "Mumbai",
        status: "In Transit",
        eta: "Today 6PM",
        risk: "Low",
        weight: "24kg",
        price: "₹1,200",
    },
    {
        id: "V1-20250302",
        client: "BlueStar Exports",
        agent: "Priya Nair",
        origin: "Delhi",
        dest: "Bangalore",
        status: "Delivered",
        eta: "Completed",
        risk: "Low",
        weight: "12kg",
        price: "₹800",
    },
    {
        id: "V1-20250303",
        client: "Metro Supplies",
        agent: "Arjun Das",
        origin: "Hyderabad",
        dest: "Chennai",
        status: "Delayed",
        eta: "Tomorrow 2PM",
        risk: "High",
        weight: "48kg",
        price: "₹3,200",
    },
    {
        id: "V1-20250304",
        client: "Sunrise Co.",
        agent: "Meena Shah",
        origin: "Mumbai",
        dest: "Pune",
        status: "Pending",
        eta: "Mar 5, 10AM",
        risk: "Medium",
        weight: "8kg",
        price: "₹500",
    },
    {
        id: "V1-20250305",
        client: "Northern Goods",
        agent: "Kiran Roy",
        origin: "Kolkata",
        dest: "Delhi",
        status: "In Transit",
        eta: "Mar 4, 8PM",
        risk: "Low",
        weight: "32kg",
        price: "₹2,100",
    },
    {
        id: "V1-20250306",
        client: "South Freight",
        agent: "Ravi Kumar",
        origin: "Bangalore",
        dest: "Hyderabad",
        status: "In Transit",
        eta: "Today 9PM",
        risk: "Medium",
        weight: "18kg",
        price: "₹1,100",
    },
    {
        id: "V1-20250307",
        client: "Coastal Cargo",
        agent: "Priya Nair",
        origin: "Kochi",
        dest: "Chennai",
        status: "Delivered",
        eta: "Completed",
        risk: "Low",
        weight: "22kg",
        price: "₹1,400",
    },
    {
        id: "V1-20250308",
        client: "Peak Logistics",
        agent: "Arjun Das",
        origin: "Mumbai",
        dest: "Delhi",
        status: "In Transit",
        eta: "Mar 5, 3PM",
        risk: "Low",
        weight: "56kg",
        price: "₹4,200",
    },
    {
        id: "V1-20250309",
        client: "Vertex Traders",
        agent: "Meena Shah",
        origin: "Delhi",
        dest: "Kolkata",
        status: "Pending",
        eta: "Mar 6, 11AM",
        risk: "Medium",
        weight: "14kg",
        price: "₹900",
    },
    {
        id: "V1-20250310",
        client: "Apex Traders",
        agent: "Kiran Roy",
        origin: "Chennai",
        dest: "Hyderabad",
        status: "Delayed",
        eta: "Mar 5, 5PM",
        risk: "High",
        weight: "38kg",
        price: "₹2,800",
    },
];

export const agents = [
    {
        id: "AGT-001",
        name: "Ravi Kumar",
        email: "ravi@cargoflow.com",
        phone: "+91 98765 43210",
        status: "Active",
        deliveries: 11,
        completed: 142,
        rate: "98.2%",
        zone: "Chennai",
        joined: "Jan 2024",
    },
    {
        id: "AGT-002",
        name: "Priya Nair",
        email: "priya@cargoflow.com",
        phone: "+91 87654 32109",
        status: "Active",
        deliveries: 9,
        completed: 198,
        rate: "100%",
        zone: "Kochi",
        joined: "Mar 2024",
    },
    {
        id: "AGT-003",
        name: "Arjun Das",
        email: "arjun@cargoflow.com",
        phone: "+91 76543 21098",
        status: "Block",
        deliveries: 6,
        completed: 87,
        rate: "83.5%",
        zone: "Hyderabad",
        joined: "Jun 2024",
    },
    {
        id: "AGT-004",
        name: "Meena Shah",
        email: "meena@cargoflow.com",
        phone: "+91 65432 10987",
        status: "Active",
        deliveries: 14,
        completed: 223,
        rate: "95.7%",
        zone: "Mumbai",
        joined: "Feb 2024",
    },
    {
        id: "AGT-005",
        name: "Kiran Roy",
        email: "kiran@cargoflow.com",
        phone: "+91 54321 09876",
        status: "Off",
        deliveries: 4,
        completed: 64,
        rate: "90.0%",
        zone: "Kolkata",
        joined: "Aug 2024",
    },
    {
        id: "AGT-006",
        name: "Sneha Gupta",
        email: "sneha@cargoflow.com",
        phone: "+91 43210 98765",
        status: "Active",
        deliveries: 8,
        completed: 176,
        rate: "97.1%",
        zone: "Delhi",
        joined: "Apr 2024",
    },
];
export const BASE_RISK_ALERTS = [
    { icon: "⚠️", label: "Route congestion — Chennai Port", border: "#FDE68A", type: "warning" },
    { icon: "🌦️", label: "Weather delay — Mumbai region", border: "#BFDBFE", type: "info" },
    { icon: "📦", label: "3 clients with overdue invoices", border: "#FECACA", type: "danger" },
];

export const statusMeta = {
    "In Transit": { bg: "#DBEAFE", color: "#1D4ED8" },
    Delivered: { bg: "#D1FAE5", color: "#065F46" },
    Delayed: { bg: "#FEE2E2", color: "#991B1B" },
    Pending: { bg: "#FEF3C7", color: "#92400E" },
};

export const clients = [
    { id: "CLT-001", name: "Apex Traders", contact: "Ramesh Kumar", email: "ramesh@apextraders.com", phone: "+91 98100 11223", city: "Chennai", shipments: 28, revenue: "₹84,000", status: "Active", joined: "Jan 2024" },
    { id: "CLT-002", name: "BlueStar Exports", contact: "Priya Singh", email: "priya@bluestar.com", phone: "+91 87200 22334", city: "Delhi", shipments: 42, revenue: "₹1,26,000", status: "Active", joined: "Feb 2024" },
    { id: "CLT-003", name: "Metro Supplies", contact: "Ankit Sharma", email: "ankit@metrosupplies.com", phone: "+91 76300 33445", city: "Hyderabad", shipments: 15, revenue: "₹48,000", status: "Overdue", joined: "Mar 2024" },
    { id: "CLT-004", name: "Sunrise Co.", contact: "Neha Patel", email: "neha@sunriseco.com", phone: "+91 65400 44556", city: "Mumbai", shipments: 9, revenue: "₹27,000", status: "Active", joined: "Apr 2024" },
    { id: "CLT-005", name: "Northern Goods", contact: "Vikram Roy", email: "vikram@northerngoods.com", phone: "+91 54500 55667", city: "Kolkata", shipments: 31, revenue: "₹93,000", status: "Active", joined: "May 2024" },
    { id: "CLT-006", name: "South Freight", contact: "Deepa Nair", email: "deepa@southfreight.com", phone: "+91 43600 66778", city: "Bangalore", shipments: 7, revenue: "₹21,000", status: "Inactive", joined: "Jun 2024" },
    { id: "CLT-007", name: "Coastal Cargo", contact: "Suresh Menon", email: "suresh@coastalcargo.com", phone: "+91 32700 77889", city: "Kochi", shipments: 19, revenue: "₹57,000", status: "Active", joined: "Jul 2024" },
    { id: "CLT-008", name: "Peak Logistics", contact: "Kavitha Iyer", email: "kavitha@peaklogistics.com", phone: "+91 21800 88990", city: "Pune", shipments: 52, revenue: "₹1,56,000", status: "Active", joined: "Aug 2024" },
];

export const monthlyData = [
    { month: "Oct", shipments: 62, delivered: 58, delayed: 4, revenue: 186000 },
    { month: "Nov", shipments: 71, delivered: 67, delayed: 4, revenue: 213000 },
    { month: "Dec", shipments: 88, delivered: 82, delayed: 6, revenue: 264000 },
    { month: "Jan", shipments: 74, delivered: 71, delayed: 3, revenue: 222000 },
    { month: "Feb", shipments: 81, delivered: 79, delayed: 2, revenue: 243000 },
    { month: "Mar", shipments: 92, delivered: 88, delayed: 4, revenue: 276000 },
];

export const recentReports = [
    { name: "February 2025 Summary", type: "Monthly", date: "Mar 1, 2025", size: "2.4 MB" },
    { name: "Q4 2024 Performance Report", type: "Quarterly", date: "Jan 5, 2025", size: "5.1 MB" },
    { name: "January 2025 Summary", type: "Monthly", date: "Feb 1, 2025", size: "2.1 MB" },
    { name: "Agent Performance – Feb", type: "Agent", date: "Mar 1, 2025", size: "1.8 MB" },
    { name: "Client Revenue – Q4", type: "Client", date: "Jan 10, 2025", size: "3.2 MB" },
];